---
- name: Setup production
  become: yes
  become_user: root
  command: bench setup production {{ dataent_user }}
  args:
    chdir: '{{ bench_path }}'

- name: Setup Sudoers
  become: yes
  become_user: root
  command: bench setup sudoers {{ dataent_user }}
  args:
    chdir: '{{ bench_path }}'

- name: Set correct permissions on bench.log
  file:
    path: '{{ bench_path }}/logs/bench.log'
    owner: '{{ dataent_user }}'
    group: '{{ dataent_user }}'
  become: yes
  become_user: root

- name: Restart the bench
  command: bench restart
  args:
    chdir: '{{ bench_path }}'
...